var namespace_sebastian_bergmann_1_1_comparator =
[
    [ "ArrayComparator", "class_sebastian_bergmann_1_1_comparator_1_1_array_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_array_comparator" ],
    [ "ArrayComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_array_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_array_comparator_test" ],
    [ "Author", "class_sebastian_bergmann_1_1_comparator_1_1_author.html", "class_sebastian_bergmann_1_1_comparator_1_1_author" ],
    [ "Book", "class_sebastian_bergmann_1_1_comparator_1_1_book.html", "class_sebastian_bergmann_1_1_comparator_1_1_book" ],
    [ "ClassWithToString", "class_sebastian_bergmann_1_1_comparator_1_1_class_with_to_string.html", "class_sebastian_bergmann_1_1_comparator_1_1_class_with_to_string" ],
    [ "Comparator", "class_sebastian_bergmann_1_1_comparator_1_1_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_comparator" ],
    [ "ComparisonFailure", "class_sebastian_bergmann_1_1_comparator_1_1_comparison_failure.html", "class_sebastian_bergmann_1_1_comparator_1_1_comparison_failure" ],
    [ "DateTimeComparator", "class_sebastian_bergmann_1_1_comparator_1_1_date_time_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_date_time_comparator" ],
    [ "DateTimeComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_date_time_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_date_time_comparator_test" ],
    [ "DOMNodeComparator", "class_sebastian_bergmann_1_1_comparator_1_1_d_o_m_node_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_d_o_m_node_comparator" ],
    [ "DOMNodeComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_d_o_m_node_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_d_o_m_node_comparator_test" ],
    [ "DoubleComparator", "class_sebastian_bergmann_1_1_comparator_1_1_double_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_double_comparator" ],
    [ "DoubleComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_double_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_double_comparator_test" ],
    [ "ExceptionComparator", "class_sebastian_bergmann_1_1_comparator_1_1_exception_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_exception_comparator" ],
    [ "ExceptionComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_exception_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_exception_comparator_test" ],
    [ "Factory", "class_sebastian_bergmann_1_1_comparator_1_1_factory.html", "class_sebastian_bergmann_1_1_comparator_1_1_factory" ],
    [ "FactoryTest", "class_sebastian_bergmann_1_1_comparator_1_1_factory_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_factory_test" ],
    [ "MockObjectComparator", "class_sebastian_bergmann_1_1_comparator_1_1_mock_object_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_mock_object_comparator" ],
    [ "MockObjectComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_mock_object_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_mock_object_comparator_test" ],
    [ "NumericComparator", "class_sebastian_bergmann_1_1_comparator_1_1_numeric_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_numeric_comparator" ],
    [ "NumericComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_numeric_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_numeric_comparator_test" ],
    [ "ObjectComparator", "class_sebastian_bergmann_1_1_comparator_1_1_object_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_object_comparator" ],
    [ "ObjectComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_object_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_object_comparator_test" ],
    [ "ResourceComparator", "class_sebastian_bergmann_1_1_comparator_1_1_resource_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_resource_comparator" ],
    [ "ResourceComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_resource_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_resource_comparator_test" ],
    [ "SampleClass", "class_sebastian_bergmann_1_1_comparator_1_1_sample_class.html", "class_sebastian_bergmann_1_1_comparator_1_1_sample_class" ],
    [ "ScalarComparator", "class_sebastian_bergmann_1_1_comparator_1_1_scalar_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_scalar_comparator" ],
    [ "ScalarComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_scalar_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_scalar_comparator_test" ],
    [ "SplObjectStorageComparator", "class_sebastian_bergmann_1_1_comparator_1_1_spl_object_storage_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_spl_object_storage_comparator" ],
    [ "SplObjectStorageComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_spl_object_storage_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_spl_object_storage_comparator_test" ],
    [ "Struct", "class_sebastian_bergmann_1_1_comparator_1_1_struct.html", "class_sebastian_bergmann_1_1_comparator_1_1_struct" ],
    [ "TestClass", "class_sebastian_bergmann_1_1_comparator_1_1_test_class.html", null ],
    [ "TestClassComparator", "class_sebastian_bergmann_1_1_comparator_1_1_test_class_comparator.html", null ],
    [ "TypeComparator", "class_sebastian_bergmann_1_1_comparator_1_1_type_comparator.html", "class_sebastian_bergmann_1_1_comparator_1_1_type_comparator" ],
    [ "TypeComparatorTest", "class_sebastian_bergmann_1_1_comparator_1_1_type_comparator_test.html", "class_sebastian_bergmann_1_1_comparator_1_1_type_comparator_test" ]
];