var searchData=
[
  ['magiccallpatch_2ephp',['MagicCallPatch.php',['../_magic_call_patch_8php.html',1,'']]],
  ['match_2ephp',['Match.php',['../_match_8php.html',1,'']]],
  ['matcher_2ephp',['Matcher.php',['../myclabs_2deep-copy_2src_2_deep_copy_2_matcher_2_matcher_8php.html',1,'(Global Namespace)'],['../phpunit_2phpunit-mock-objects_2src_2_framework_2_mock_object_2_matcher_8php.html',1,'(Global Namespace)']]],
  ['matchercollection_2ephp',['MatcherCollection.php',['../_matcher_collection_8php.html',1,'']]],
  ['mbstring_2ephp',['mbstring.php',['../mbstring_8php.html',1,'']]],
  ['memcached_2ephp',['memcached.php',['../memcached_8php.html',1,'']]],
  ['memoryefficientimplementationtest_2ephp',['MemoryEfficientImplementationTest.php',['../_memory_efficient_implementation_test_8php.html',1,'']]],
  ['memoryefficientlongestcommonsubsequenceimplementation_2ephp',['MemoryEfficientLongestCommonSubsequenceImplementation.php',['../_memory_efficient_longest_common_subsequence_implementation_8php.html',1,'']]],
  ['method_2ephp',['Method.php',['../phpdocumentor_2reflection-docblock_2src_2_doc_block_2_tags_2_method_8php.html',1,'(Global Namespace)'],['../phpunit_2php-code-coverage_2src_2_report_2_xml_2_method_8php.html',1,'(Global Namespace)']]],
  ['methodcallback_2ephp',['MethodCallback.php',['../_method_callback_8php.html',1,'']]],
  ['methodcallbackbyreference_2ephp',['MethodCallbackByReference.php',['../_method_callback_by_reference_8php.html',1,'']]],
  ['methodname_2ephp',['MethodName.php',['../_method_name_8php.html',1,'']]],
  ['methodnamematch_2ephp',['MethodNameMatch.php',['../_method_name_match_8php.html',1,'']]],
  ['methodnode_2ephp',['MethodNode.php',['../_method_node_8php.html',1,'']]],
  ['methodnotextendableexception_2ephp',['MethodNotExtendableException.php',['../_method_not_extendable_exception_8php.html',1,'']]],
  ['methodnotfoundexception_2ephp',['MethodNotFoundException.php',['../_method_not_found_exception_8php.html',1,'']]],
  ['methodprophecy_2ephp',['MethodProphecy.php',['../_method_prophecy_8php.html',1,'']]],
  ['methodprophecyexception_2ephp',['MethodProphecyException.php',['../_method_prophecy_exception_8php.html',1,'']]],
  ['methodtagretrieverinterface_2ephp',['MethodTagRetrieverInterface.php',['../_method_tag_retriever_interface_8php.html',1,'']]],
  ['migration_2ephp',['migration.php',['../application_2config_2migration_8php.html',1,'(Global Namespace)'],['../system_2libraries_2migration_8php.html',1,'(Global Namespace)']]],
  ['migration_5flang_2ephp',['migration_lang.php',['../migration__lang_8php.html',1,'']]],
  ['mimes_2ephp',['mimes.php',['../mimes_8php.html',1,'']]],
  ['missingcoversannotationexception_2ephp',['MissingCoversAnnotationException.php',['../php-code-coverage_2src_2_exception_2_missing_covers_annotation_exception_8php.html',1,'(Global Namespace)'],['../phpunit_2src_2_framework_2_missing_covers_annotation_exception_8php.html',1,'(Global Namespace)']]],
  ['mixed_5f_2ephp',['Mixed_.php',['../_mixed___8php.html',1,'']]],
  ['mockable_2ephp',['Mockable.php',['../tests_2__files_2_mockable_8php.html',1,'(Global Namespace)'],['../mock-objects_2tests_2__fixture_2_mockable_8php.html',1,'(Global Namespace)']]],
  ['mockbuilder_2ephp',['MockBuilder.php',['../_mock_builder_8php.html',1,'']]],
  ['mockbuildertest_2ephp',['MockBuilderTest.php',['../_mock_builder_test_8php.html',1,'']]],
  ['mockobject_2ephp',['MockObject.php',['../_mock_object_8php.html',1,'']]],
  ['mockobjectcomparator_2ephp',['MockObjectComparator.php',['../_mock_object_comparator_8php.html',1,'']]],
  ['mockobjectcomparatortest_2ephp',['MockObjectComparatorTest.php',['../_mock_object_comparator_test_8php.html',1,'']]],
  ['mockobjecttest_2ephp',['MockObjectTest.php',['../_mock_object_test_8php.html',1,'']]],
  ['mockrunner_2ephp',['MockRunner.php',['../_mock_runner_8php.html',1,'']]],
  ['mocktestinterface_2ephp',['MockTestInterface.php',['../_mock_test_interface_8php.html',1,'']]],
  ['model_2ephp',['Model.php',['../_model_8php.html',1,'']]],
  ['mssql_5fdriver_2ephp',['mssql_driver.php',['../mssql__driver_8php.html',1,'']]],
  ['mssql_5fforge_2ephp',['mssql_forge.php',['../mssql__forge_8php.html',1,'']]],
  ['mssql_5fresult_2ephp',['mssql_result.php',['../mssql__result_8php.html',1,'']]],
  ['mssql_5futility_2ephp',['mssql_utility.php',['../mssql__utility_8php.html',1,'']]],
  ['multidependencytest_2ephp',['MultiDependencyTest.php',['../_multi_dependency_test_8php.html',1,'']]],
  ['multipledataprovidertest_2ephp',['MultipleDataProviderTest.php',['../_multiple_data_provider_test_8php.html',1,'']]],
  ['multiplenamespaceswithoneclassusingbraces_2ephp',['multipleNamespacesWithOneClassUsingBraces.php',['../multiple_namespaces_with_one_class_using_braces_8php.html',1,'']]],
  ['multiplenamespaceswithoneclassusingnonbracesyntax_2ephp',['multipleNamespacesWithOneClassUsingNonBraceSyntax.php',['../multiple_namespaces_with_one_class_using_non_brace_syntax_8php.html',1,'']]],
  ['mycommand_2ephp',['MyCommand.php',['../_my_command_8php.html',1,'']]],
  ['mysql_5fdriver_2ephp',['mysql_driver.php',['../mysql__driver_8php.html',1,'']]],
  ['mysql_5fforge_2ephp',['mysql_forge.php',['../mysql__forge_8php.html',1,'']]],
  ['mysql_5fresult_2ephp',['mysql_result.php',['../mysql__result_8php.html',1,'']]],
  ['mysql_5futility_2ephp',['mysql_utility.php',['../mysql__utility_8php.html',1,'']]],
  ['mysqli_5fdriver_2ephp',['mysqli_driver.php',['../mysqli__driver_8php.html',1,'']]],
  ['mysqli_5fforge_2ephp',['mysqli_forge.php',['../mysqli__forge_8php.html',1,'']]],
  ['mysqli_5fresult_2ephp',['mysqli_result.php',['../mysqli__result_8php.html',1,'']]],
  ['mysqli_5futility_2ephp',['mysqli_utility.php',['../mysqli__utility_8php.html',1,'']]]
];
